apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-taskrun
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image
  params:
  - name: IMAGE
    value: "rahafog1/orders"
  resources:
    inputs:
    - name: orders
      resourceRef:
        name: orders
