apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  resources:
    - name: orders-resource
      type: git
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      type: string
    - name: IMAGE-db
      description: Name (reference) of the database image to build.
      type: string
    - name: pathToYamlFile
      description: The path to the yaml file to deploy
      type: string
    - name: imageUrl
      description: Url of image repository
      type: string
    - name: imageTag
      description: Tag to apply to the built image
      type: string
    - name: pathToYamlFile-db
      description: The path to the database yaml file to deploy
      type: string
    - name: imageUrl-db
      description: Url of image repository
      type: string
    - name: imageTag-db
      description: Tag to apply to the image
      type: string
  tasks:
  - name: run-db
    taskRef:
      name: orders-db-deploy
    params:
      - name: pathToYamlFile-db
        value:  "$(params.pathToYamlFile-db)"
      - name: imageUrl-db
        value: "$(params.imageUrl-db)"
      - name: imageTag-db
        value: "$(params.imageTag-db)"
    resources: 
      inputs:
        - name: orders-resource
          resource: orders-resource 
  - name: build-push-image
    taskRef:
      name: orders
    runAfter:
      - run-db
    params:
      - name: IMAGE
        value : "$(params.IMAGE)"
    resources:
      inputs: 
        - name: orders-resource
          resource: orders-resource
  - name: deploy-to-cluster
    taskRef: 
      name: orders-deploy
    runAfter:
      - run-db
      - build-push-image
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value : "$(params.imageTag)"
    resources:
      inputs: 
        - name: orders-resource
          resource: orders-resource
