apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: orders
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/rahafog/SDA-level3project.git/orders
