apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: orders
  params:
  - name: IMAGE
    value: "rahafog1/orders"
  resources:
    inputs : 
    - name: orders-resource
      resourceRef: 
        name: orders-resource
