apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: payment-pipelinerun 
spec:
  pipelineRef:
    name: payment-pipeline
  resources:
    - name: payment-resource
      resourceRef:
        name: payment-resource
  params:
    - name: CONTEXT
      value: "/workspace/payment-resource/payment"
    - name: DOCKERFILE
      value: "/workspace/payment-resource/payment/Dockerfile"
    - name: pathToYamlFile
      value: "payment-resource/payment/payment-dep.yaml"
    - name: imageUrl
      value: "rahafog1/payment"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "rahafog1/payment"
      
  serviceAccountName: docker1
