apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: payment
  params:
  - name: IMAGE
    value: "rahafog1/payment"
  resources:
    inputs : 
    - name: payment-resource
      resourceRef: 
        name: payment-resource
