apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: docker-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: shipping
  params:
  - name: IMAGE
    value: "rahafog1/shipping"
  resources:
    inputs :
    - name: shipping-resource
      resourceRef: 
        name: shipping-resource
