apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: queue-resource
spec:
  type: git
  params:
    - name: revision 
      value: main
    - name: url
      value: https://github.com/rahafog/level3project.git
