apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: front-end
  params:
  - name: IMAGE
    value: "rahafog1/front-end"
  resources:
    inputs :
    - name: front-resource
      resourceRef: 
        name: front-resource
