build:
	 kubectl apply -f ./resource.yaml -n test
	 kubectl apply -f ./task.yaml -n test
	 kubectl apply -f ./carts-dep.yaml -n test
	 kubectl apply -f ./pipeline.yaml -n test
	 kubectl apply -f ./pipelinerun.yaml -n test


delete:
	kubectl delete -f ./resource.yaml -n test
	kubectl delete -f ./task.yaml -n test
	kubectl delete -f ./carts-dep.yaml -n test
	kubectl delete -f ./pipeline.yaml -n test
	kubectl delete -f ./pipelinerun.yaml -n test
