apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: carts-pipelinerun 
spec:
  pipelineRef:
    name: carts-pipeline
  resources:
    - name: carts-resource
      resourceRef:
        name: carts-resource
  params:
    - name: IMAGE-db
      value: "rahafog1/carts-db"
    - name: IMAGE
      value: "rahafog1/carts"
    - name: pathToYamlFile
      value: "carts-resource/carts/carts-dep.yaml"
    - name: imageUrl
      value: "rahafog1/carts"
    - name: imageTag
      value: "latest"
    - name: pathToYamlFile-db
      value: "carts-resource/carts/carts-dep.yaml"
    - name: imageUrl-db
      value: "rahafog1/carts-db"
    - name: imageTag-db
      value: "latest"
      
  serviceAccountName: docker1
