apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: carts
  params:
  - name: IMAGE
    value: "rahafog1/carts"
  resources:
    inputs : 
    - name: carts-resource
      resourceRef: 
        name: carts-resource
