apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: carts-db-deploy
spec:
  resources:
    inputs: 
    - name: carts-resource
      type: git
  params:
  - name: pathToYamlFile-db
    description: The path to the yaml file to deploy within the git source
  - name: imageUrl-db
    description: Url of image repository
  - name: imageTag-db
    description: Tag of the images to be used.
  steps:
  - name: update-yaml
    image: alpine
    command: ["sed"]
    args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;$(inputs.params.imageUrl-db):$(inputs.params.imageTag-db);g"
      - "/workspace/$(inputs.params.pathToYamlFile-db)"
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "/workspace/$(inputs.params.pathToYamlFile-db)"
