apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-task-run
spec:
  serviceAccountName: docker-service
  taskRef:
    name: build-docker-image-from-git
  params:
    - name: pathToDockerFile
      value: Dockerfile
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: orders-git
    outputs:
      - name: builtImage
        resourceRef:
          name: orders-docker
