apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: e2e-pipelinerun 
spec:
  pipelineRef:
    name: e2e-pipeline
  resources:
    - name: e2e-resource
      resourceRef:
        name: e2e-resource
  params:
    - name: imageUrl
      value: "rahafog1/e2e-js-test"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "rahafog1/e2e-js-test"
    - name: pathToYamlFile
      value: "e2e-resource/e2e-js-test/deploy-to-prod.yaml"
      
  serviceAccountName: docker1
