apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: docker-runner
spec:
  serviceAccountName: docker2
  taskRef:
    name: catalogue
  params:
  - name: IMAGE
    value: "rahafog1/catalogue"
  resources:
    inputs :
    - name: level3project
      resourceRef: 
        name: level3project
