apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-runner
spec:
  serviceAccountName: docker1
  taskRef:
    name: catalogue
  params:
  - name: IMAGE
    value: "rahafog1/catalogue"
  resources:
    inputs : 
    - name: catalogue-resource
      resourceRef:  
        name: catalogue-resource
